server:
    port: 8080
spring:
    application:
        name: customer
    datasource:
        password: password
        url: jdbc:mysql://localhost:7013/mdb
        username: root
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL57Dialect
                format_sql: true
        show-sql: true
